#!/usr/bin/env python3
import os
import ast

def main():
    base_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "gallery_dl")

    valid_keys = set()
    valid_keys.update(["extractor", "downloader", "output", "postprocessor", "cache"])
    valid_keys.update(["#"]) # Comment pseudo-key

    for root, _, files in os.walk(base_dir):
        for file in files:
            if not file.endswith(".py") or file == "config_schema.py":
                continue
            path = os.path.join(root, file)
            try:
                with open(path, "r", encoding="utf-8") as fp:
                    src = fp.read()
                tree = ast.parse(src)
                for node in ast.walk(tree):
                    if isinstance(node, ast.Constant) and isinstance(node.value, str):
                        valid_keys.add(node.value)
            except Exception:
                pass

    out_path = os.path.join(base_dir, "config_schema.py")
    with open(out_path, "w", encoding="utf-8") as fp:
        fp.write("# Auto-generated by scripts/generate_config_schema.py\n")
        fp.write("VALID_KEYS = {\n")
        for k in sorted(valid_keys):
            # Write it carefully to handle escapes
            fp.write(f"    {repr(k)},\n")
        fp.write("}\n")

if __name__ == "__main__":
    main()
